//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScheduleImporter.AddIn.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkScheduleTemplate")]
        public string LogicalFileNameOfWorkScheduleTemplate {
            get {
                return ((string)(this["LogicalFileNameOfWorkScheduleTemplate"]));
            }
            set {
                this["LogicalFileNameOfWorkScheduleTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SIM")]
        public string CONFIG_SHEET_TRUE_VALUE {
            get {
                return ((string)(this["CONFIG_SHEET_TRUE_VALUE"]));
            }
            set {
                this["CONFIG_SHEET_TRUE_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NÃO")]
        public string CONFIG_SHEET_FALSE_VALUE {
            get {
                return ((string)(this["CONFIG_SHEET_FALSE_VALUE"]));
            }
            set {
                this["CONFIG_SHEET_FALSE_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.ACE.OLEDB.12.0;")]
        public string EXCEL_PROVIDER {
            get {
                return ((string)(this["EXCEL_PROVIDER"]));
            }
            set {
                this["EXCEL_PROVIDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Excel 12.0 XML")]
        public string EXCEL_EXTENDED_PROPERTIES {
            get {
                return ((string)(this["EXCEL_EXTENDED_PROPERTIES"]));
            }
            set {
                this["EXCEL_EXTENDED_PROPERTIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Share Exclusive")]
        public string EXCEL_MODE {
            get {
                return ((string)(this["EXCEL_MODE"]));
            }
            set {
                this["EXCEL_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMddHHmmss")]
        public string DB_DATE_TIME_STAMP_FORMAT {
            get {
                return ((string)(this["DB_DATE_TIME_STAMP_FORMAT"]));
            }
            set {
                this["DB_DATE_TIME_STAMP_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string DB_TRUE_VALUE {
            get {
                return ((string)(this["DB_TRUE_VALUE"]));
            }
            set {
                this["DB_TRUE_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string DB_FALSE_VALUE {
            get {
                return ((string)(this["DB_FALSE_VALUE"]));
            }
            set {
                this["DB_FALSE_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escala")]
        public string SHEET_NAME_WORK_SCHEDULE_MAIN {
            get {
                return ((string)(this["SHEET_NAME_WORK_SCHEDULE_MAIN"]));
            }
            set {
                this["SHEET_NAME_WORK_SCHEDULE_MAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AM")]
        public string SHEET_NAME_UNIT {
            get {
                return ((string)(this["SHEET_NAME_UNIT"]));
            }
            set {
                this["SHEET_NAME_UNIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Base")]
        public string SHEET_NAME_STATION {
            get {
                return ((string)(this["SHEET_NAME_STATION"]));
            }
            set {
                this["SHEET_NAME_STATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Funcionarios")]
        public string SHEET_NAME_EMPLOYEE {
            get {
                return ((string)(this["SHEET_NAME_EMPLOYEE"]));
            }
            set {
                this["SHEET_NAME_EMPLOYEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config")]
        public string SHEET_NAME_CONFIG {
            get {
                return ((string)(this["SHEET_NAME_CONFIG"]));
            }
            set {
                this["SHEET_NAME_CONFIG"] = value;
            }
        }
    }
}
