//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScheduleImporter.AddIn.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkScheduleImporter.AddIn.Views.ViewResource", typeof(ViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixar XLS importação.
        /// </summary>
        public static string BUTTON_DOWNLOAD {
            get {
                return ResourceManager.GetString("BUTTON_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixar Modelo.
        /// </summary>
        public static string BUTTON_DOWNLOAD_TOOL_TIP {
            get {
                return ResourceManager.GetString("BUTTON_DOWNLOAD_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BUTTON_GO_BACK {
            get {
                return ResourceManager.GetString("BUTTON_GO_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BUTTON_GO_BACK_TOOL_TIP {
            get {
                return ResourceManager.GetString("BUTTON_GO_BACK_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        public static string BUTTON_IMPORT {
            get {
                return ResourceManager.GetString("BUTTON_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        public static string BUTTON_IMPORT_TOOL_TIP {
            get {
                return ResourceManager.GetString("BUTTON_IMPORT_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar.
        /// </summary>
        public static string BUTTON_VALIDATE {
            get {
                return ResourceManager.GetString("BUTTON_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar.
        /// </summary>
        public static string BUTTON_VALIDATE_TOOL_TIP {
            get {
                return ResourceManager.GetString("BUTTON_VALIDATE_TOOL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar escala periódica.
        /// </summary>
        public static string CHECK_BOX_CREATE_PERIODIC_WORK_SCHEDULE {
            get {
                return ResourceManager.GetString("CHECK_BOX_CREATE_PERIODIC_WORK_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipe.
        /// </summary>
        public static string COLUMN_CREW {
            get {
                return ResourceManager.GetString("COLUMN_CREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string COLUMN_DATE {
            get {
                return ResourceManager.GetString("COLUMN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha.
        /// </summary>
        public static string COLUMN_ROW {
            get {
                return ResourceManager.GetString("COLUMN_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        public static string COLUMN_SHIFT {
            get {
                return ResourceManager.GetString("COLUMN_SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string COLUMN_TYPE {
            get {
                return ResourceManager.GetString("COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string COLUMN_UNIT {
            get {
                return ResourceManager.GetString("COLUMN_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros/alertas.
        /// </summary>
        public static string COLUMN_WARNING_AND_ERRORS {
            get {
                return ResourceManager.GetString("COLUMN_WARNING_AND_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo: .
        /// </summary>
        public static string FILE_LABEL {
            get {
                return ResourceManager.GetString("FILE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importação de Escala.
        /// </summary>
        public static string IMPORTING_DIALOG_MAIN_TITLE {
            get {
                return ResourceManager.GetString("IMPORTING_DIALOG_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Escala.
        /// </summary>
        public static string IMPORTING_DIALOG_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("IMPORTING_DIALOG_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final: .
        /// </summary>
        public static string PERIODIC_WORK_SCHEDULE_FINAL_DATE {
            get {
                return ResourceManager.GetString("PERIODIC_WORK_SCHEDULE_FINAL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalas Periódicas.
        /// </summary>
        public static string PERIODIC_WORK_SCHEDULE_GROUB_BOX {
            get {
                return ResourceManager.GetString("PERIODIC_WORK_SCHEDULE_GROUB_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de importação: .
        /// </summary>
        public static string PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE {
            get {
                return ResourceManager.GetString("PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação de Escala.
        /// </summary>
        public static string PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE_CREATING {
            get {
                return ResourceManager.GetString("PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE_CREATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação de Escala (compondo equipes).
        /// </summary>
        public static string PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE_MERGING {
            get {
                return ResourceManager.GetString("PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE_MERGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização de Escala.
        /// </summary>
        public static string PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE_UPDATING {
            get {
                return ResourceManager.GetString("PERIODIC_WORK_SCHEDULE_IMPORTING_TYPE_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial: .
        /// </summary>
        public static string PERIODIC_WORK_SCHEDULE_INITIAL_DATE {
            get {
                return ResourceManager.GetString("PERIODIC_WORK_SCHEDULE_INITIAL_DATE", resourceCulture);
            }
        }
    }
}
