//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScheduleImporter.AddIn.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkScheduleImporter.AddIn.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique no botão Importar para enviar a escala..
        /// </summary>
        internal static string ALERT_MESSAGE_WHEN_NO_ERRORS {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_WHEN_NO_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituição de escala antiga.
        /// </summary>
        internal static string CONFLICT_WITH_PREVIOUS_DATA_MESSAGE {
            get {
                return ResourceManager.GetString("CONFLICT_WITH_PREVIOUS_DATA_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de caracteres excedido.
        /// </summary>
        internal static string DATA_LENGTH_OVERFLOW_MESSAGE {
            get {
                return ResourceManager.GetString("DATA_LENGTH_OVERFLOW_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dado não preenchido.
        /// </summary>
        internal static string DATA_SHOULD_BE_FILLED_MESSAGE {
            get {
                return ResourceManager.GetString("DATA_SHOULD_BE_FILLED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário duplicado no mesmo dia e turno.
        /// </summary>
        internal static string EMPLOYEE_DUPLICATED_AT_DAY_MESSAGE {
            get {
                return ResourceManager.GetString("EMPLOYEE_DUPLICATED_AT_DAY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário duplicado na mesma viatura.
        /// </summary>
        internal static string EMPLOYEE_DUPLICATED_ON_UNIT_MESSAGE {
            get {
                return ResourceManager.GetString("EMPLOYEE_DUPLICATED_ON_UNIT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipe não equivalente ao tipo da viatura.
        /// </summary>
        internal static string INVALID_CREW_FORMATION_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_CREW_FORMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipe não permitida no tipo da viatura.
        /// </summary>
        internal static string INVALID_CREW_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_CREW_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de data inválido.
        /// </summary>
        internal static string INVALID_DATE_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_DATE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário inválido.
        /// </summary>
        internal static string INVALID_EMPLOYEE_ID_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_EMPLOYEE_ID_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base inválida.
        /// </summary>
        internal static string INVALID_STATION_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_STATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viatura inválida.
        /// </summary>
        internal static string INVALID_UNIT_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_UNIT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno inválido.
        /// </summary>
        internal static string INVALID_WORKSHIFT_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_WORKSHIFT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dado obrigatório não informado.
        /// </summary>
        internal static string MISSED_DATA_MESSAGE {
            get {
                return ResourceManager.GetString("MISSED_DATA_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilha não encontrada.
        /// </summary>
        internal static string SHEET_NAME_NOT_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("SHEET_NAME_NOT_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viatura duplicada no mesmo dia e turno.
        /// </summary>
        internal static string UNIT_DUPLICATED_AT_DAY_MESSAGE {
            get {
                return ResourceManager.GetString("UNIT_DUPLICATED_AT_DAY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validado.
        /// </summary>
        internal static string VALIDATED_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de data errado.
        /// </summary>
        internal static string WRONG_DATA_FORMAT_MESSAGE {
            get {
                return ResourceManager.GetString("WRONG_DATA_FORMAT_MESSAGE", resourceCulture);
            }
        }
    }
}
