//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScheduleImporter.AddIn.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkScheduleImporter.AddIn.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aux1.
        /// </summary>
        internal static string AUX_1_ALIAS {
            get {
                return ResourceManager.GetString("AUX_1_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aux2.
        /// </summary>
        internal static string AUX_2_ALIAS {
            get {
                return ResourceManager.GetString("AUX_2_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aux3.
        /// </summary>
        internal static string AUX_3_ALIAS {
            get {
                return ResourceManager.GetString("AUX_3_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        internal static string CELL_PHONE_COL_NAME {
            get {
                return ResourceManager.GetString("CELL_PHONE_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF do médico.
        /// </summary>
        internal static string DOCTOR_COL_NAME {
            get {
                return ResourceManager.GetString("DOCTOR_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot.
        /// </summary>
        internal static string DRIVER_ALIAS {
            get {
                return ResourceManager.GetString("DRIVER_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF do condutor.
        /// </summary>
        internal static string DRIVER_COL_NAME {
            get {
                return ResourceManager.GetString("DRIVER_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF.
        /// </summary>
        internal static string EMPLOYEE_LABEL {
            get {
                return ResourceManager.GetString("EMPLOYEE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF do primeiro auxiliar.
        /// </summary>
        internal static string FIRST_AUXILIAR_COL_NAME {
            get {
                return ResourceManager.GetString("FIRST_AUXILIAR_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA SIM - DIA NÃO.
        /// </summary>
        internal static string FREQUENCE_TYPE_ALTERNABLE_DAY_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREQUENCE_TYPE_ALTERNABLE_DAY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIÁRIA.
        /// </summary>
        internal static string FREQUENCE_TYPE_DAILY_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREQUENCE_TYPE_DAILY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 VEZ.
        /// </summary>
        internal static string FREQUENCE_TYPE_ONCE_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREQUENCE_TYPE_ONCE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMANAL.
        /// </summary>
        internal static string FREQUENCE_TYPE_WEEKLY_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREQUENCE_TYPE_WEEKLY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA ÚTIL.
        /// </summary>
        internal static string FREQUENCE_TYPE_WORK_DAY_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREQUENCE_TYPE_WORK_DAY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É Viatura do tipo URAM.
        /// </summary>
        internal static string IS_URAM_COL_NAME {
            get {
                return ResourceManager.GetString("IS_URAM_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méd.
        /// </summary>
        internal static string MEDIC_ALIAS {
            get {
                return ResourceManager.GetString("MEDIC_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enf.
        /// </summary>
        internal static string NURSE_ALIAS {
            get {
                return ResourceManager.GetString("NURSE_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF do enfermeiro.
        /// </summary>
        internal static string NURSE_COL_NAME {
            get {
                return ResourceManager.GetString("NURSE_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        internal static string REMARK_COL_NAME {
            get {
                return ResourceManager.GetString("REMARK_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF do segundo auxiliar.
        /// </summary>
        internal static string SECOND_AUXILIAR_COL_NAME {
            get {
                return ResourceManager.GetString("SECOND_AUXILIAR_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string SHIFT_DATE_COL_NAME {
            get {
                return ResourceManager.GetString("SHIFT_DATE_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID da Base.
        /// </summary>
        internal static string STATION_ID_COL_NAME {
            get {
                return ResourceManager.GetString("STATION_ID_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string STATION_NAME_COL_NAME {
            get {
                return ResourceManager.GetString("STATION_NAME_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF do terceiro auxiliar.
        /// </summary>
        internal static string THIRD_AUXILIAR_COL_NAME {
            get {
                return ResourceManager.GetString("THIRD_AUXILIAR_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viatura.
        /// </summary>
        internal static string UNIT_ID_COL_NAME {
            get {
                return ResourceManager.GetString("UNIT_ID_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        internal static string WORKSHIF_LABEL_COL_NAME {
            get {
                return ResourceManager.GetString("WORKSHIF_LABEL_COL_NAME", resourceCulture);
            }
        }
    }
}
