//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScheduleImporter.AddIn.ViewModels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkScheduleImporter.AddIn.ViewModels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante a validação do arquivo.
        /// </summary>
        internal static string ALERT_MESSAGE_ERROR_FILE_VALIDATING {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_ERROR_FILE_VALIDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante a geração do arquivo (obs: é necessário que o Excel esteja instalado).
        /// </summary>
        internal static string ALERT_MESSAGE_ERROR_GENERATING_FILE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_ERROR_GENERATING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao gerar as escalas periódicas.
        /// </summary>
        internal static string ALERT_MESSAGE_ERROR_GENERATING_PERIODIC_WORK_SCHEDULE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_ERROR_GENERATING_PERIODIC_WORK_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na Importação.
        /// </summary>
        internal static string ALERT_MESSAGE_ERROR_IMPORTING {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_ERROR_IMPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe escala em.
        /// </summary>
        internal static string ALERT_MESSAGE_ERROR_WORK_SCHEDULE_NOT_EXISTS_TO_DATE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_ERROR_WORK_SCHEDULE_NOT_EXISTS_TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para a AM.
        /// </summary>
        internal static string ALERT_MESSAGE_ERROR_WORK_SCHEDULE_NOT_EXISTS_TO_UNIT {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_ERROR_WORK_SCHEDULE_NOT_EXISTS_TO_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversão para o mapa força de viatura falhou.
        /// </summary>
        internal static string ALERT_MESSAGE_ERROR_WORK_SCHEDULE_UNIT_CONVERSION {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_ERROR_WORK_SCHEDULE_UNIT_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A frequência de datas deve ser informada em todas as escalas da planilha.\nFavor verificar a planilha de importação..
        /// </summary>
        internal static string ALERT_MESSAGE_MISSED_DATE_FREQUENCE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_MISSED_DATE_FREQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo gerado com sucesso.
        /// </summary>
        internal static string ALERT_MESSAGE_SUCCESS_GENERATING_FILE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_SUCCESS_GENERATING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importação finalizada com sucesso..
        /// </summary>
        internal static string ALERT_MESSAGE_SUCCESS_IMPORTING {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_SUCCESS_IMPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial de importação não pode ser maior que a data final..
        /// </summary>
        internal static string ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_INVERTED_DATES {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_INVERTED_DATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para importação de escalas periódicas, é obrigatório informar o tipo de importação..
        /// </summary>
        internal static string ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_MISSED_IMPORTING_TYPE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_MISSED_IMPORTING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial de importação deve iniciar no mínimo a partir de amanhã..
        /// </summary>
        internal static string ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_PAST_DATE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_PAST_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para importação de escalas periódicas, é obrigatório informar o período de datas..
        /// </summary>
        internal static string ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_REQUIRED_DATE {
            get {
                return ResourceManager.GetString("ALERT_MESSAGE_VALIDATING_PERIODIC_WORK_SCHEDULE_REQUIRED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando arquivo modelo.
        /// </summary>
        internal static string DIALOG_MESSAGE_GENERATING_FILE {
            get {
                return ResourceManager.GetString("DIALOG_MESSAGE_GENERATING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importando escala.
        /// </summary>
        internal static string DIALOG_MESSAGE_IMPORTING_WORK_SCHEDULE {
            get {
                return ResourceManager.GetString("DIALOG_MESSAGE_IMPORTING_WORK_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validando escala.
        /// </summary>
        internal static string DIALOG_MESSAGE_VALIDATING_WORK_SCHEDULE {
            get {
                return ResourceManager.GetString("DIALOG_MESSAGE_VALIDATING_WORK_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde....
        /// </summary>
        internal static string DIALOG_MESSAGE_WAITING {
            get {
                return ResourceManager.GetString("DIALOG_MESSAGE_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala_.
        /// </summary>
        internal static string OUT_FILE_PREFIX_NAME {
            get {
                return ResourceManager.GetString("OUT_FILE_PREFIX_NAME", resourceCulture);
            }
        }
    }
}
