//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScheduleImporter.AddIn.ViewModels.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAMU")]
        public string AGENCY_ID {
            get {
                return ((string)(this["AGENCY_ID"]));
            }
            set {
                this["AGENCY_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMdd")]
        public string OUT_FILE_SUFFIX_DATE_FORMAT {
            get {
                return ((string)(this["OUT_FILE_SUFFIX_DATE_FORMAT"]));
            }
            set {
                this["OUT_FILE_SUFFIX_DATE_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xlsm")]
        public string OPEN_FILE_DIALOG_DEFAUL_EXTENSION {
            get {
                return ((string)(this["OPEN_FILE_DIALOG_DEFAUL_EXTENSION"]));
            }
            set {
                this["OPEN_FILE_DIALOG_DEFAUL_EXTENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arquivos do Excel|*.xls;*.xlsx;*.xlsm")]
        public string OPEN_FILE_DIALOG_FILTER {
            get {
                return ((string)(this["OPEN_FILE_DIALOG_FILTER"]));
            }
            set {
                this["OPEN_FILE_DIALOG_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Importação de arquivo")]
        public string OPEN_FILE_DIALOG_TITLE {
            get {
                return ((string)(this["OPEN_FILE_DIALOG_TITLE"]));
            }
            set {
                this["OPEN_FILE_DIALOG_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xlsm")]
        public string SAVE_FILE_DIALOG_DEFAUL_EXTENSION {
            get {
                return ((string)(this["SAVE_FILE_DIALOG_DEFAUL_EXTENSION"]));
            }
            set {
                this["SAVE_FILE_DIALOG_DEFAUL_EXTENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arquivos do Excel|*.xls;*.xlsx;*.xlsm")]
        public string SAVE_FILE_DIALOG_FILTER {
            get {
                return ((string)(this["SAVE_FILE_DIALOG_FILTER"]));
            }
            set {
                this["SAVE_FILE_DIALOG_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Salve como")]
        public string SAVE_FILE_DIALOG_TITLE {
            get {
                return ((string)(this["SAVE_FILE_DIALOG_TITLE"]));
            }
            set {
                this["SAVE_FILE_DIALOG_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd/MM/yyy")]
        public string DATE_FORMAT {
            get {
                return ((string)(this["DATE_FORMAT"]));
            }
            set {
                this["DATE_FORMAT"] = value;
            }
        }
    }
}
